#-------------------------------------------------------
# PROD环境配置区域
#-------------------------------------------------------
# 重要说明
# 此配置区域仅在PROD环境中生效，只能定义测试环境中默认且长期不变
# 的配置项，例如生产环境中的通用超时时间等，外部资源如数据库连接
# 等请务必通过Apollo配置中心进行配置，切勿在此文件中定义
#-------------------------------------------------------

# ----- 作业调度 生产环境配置 -----
lianjia-schedule:
  enabled: true
  env: official_prod
  token: xxxxxxxxxxxxxxxx
lianjia:
# ----- kms动态密钥管理组件 http://weapons.ke.com/project/6658/wiki/page/21427 -----
  kms:
    client:
      enabled: false
      timeout: 2000
      endpoint: http://127.0.0.1:28894
      spareEndpoint: http://key-agent.sec.ke.com
      service-id: ${spring.application.name}
# ----- Openiam验签鉴权组件(供服务提供方使用) http://weapons.ke.com/project/1402/wiki/page/18528 -----
  openiam:
    client:
      enabled: false
      # 请在服务云上生成生产环境的ak/sk
      access-key-id: <your-access-key-id>
      access-key-secret: <your-access-key-secret>
      target-uri: discovery://openiam
    validation:
      principal-detection-strategy: auto_detect_when_miss
      default-fallback-strategy: accept
      default-validation-strategy: authentication
      # 请在服务云上IAM接入向导处获取生产环境的资源/动作前缀
      resource-prefix: <your-resource-prefix>
      action-prefix: <your-action-prefix>
      http:
        enabled: true
        filter-uri: /api/**
api:
# ----- api-signature请求加签组件(供服务调用方使用) http://weapons.ke.com/project/1402/wiki/page/18501 -----
  signature:
    feign:
      keychains:
        example: { access-key-id: 123, access-key-secret: 456 }

# ----- 日志级别配置 生产环境 -----
logging:
  level:
    root: INFO
    org:
      springframework: INFO
